"""Remove stored channel ids and guild ids
This fixes d91da36b46a1 (unify rotation and votable map pools)
It partially removed channel_id and guild_id which led to bugs making finishing games impossible

Revision ID: 9e790b5beb2d
Revises: d91da36b46a1
Create Date: 2023-04-16 16:47:18.922741

"""
import logging

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e790b5beb2d"
down_revision = "d91da36b46a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_player", schema=None) as batch_op:
        batch_op.drop_column("channel_id")

    with op.batch_alter_table("queue_waitlist", schema=None) as batch_op:
        batch_op.drop_column("guild_id")

    with op.batch_alter_table("vote_passed_waitlist", schema=None) as batch_op:
        batch_op.drop_column("channel_id")
        batch_op.drop_column("guild_id")

    # ### end Alembic commands ###


def downgrade():
    logging.warning("Downgrading clears the queue, all votes and all waitlists!")

    op.execute("DELETE FROM map_vote")
    op.execute("DELETE FROM skip_map_vote")
    op.execute("DELETE FROM vote_passed_waitlist_player")
    op.execute("DELETE FROM vote_passed_waitlist")
    op.execute("DELETE FROM queue_waitlist_player")
    op.execute("DELETE FROM queue_waitlist")
    op.execute("DELETE FROM queue_player")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vote_passed_waitlist", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "guild_id", sa.BIGINT(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "channel_id", sa.BIGINT(), autoincrement=False, nullable=False
            )
        )

    with op.batch_alter_table("queue_waitlist", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "guild_id", sa.BIGINT(), autoincrement=False, nullable=False
            )
        )

    with op.batch_alter_table("queue_player", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "channel_id", sa.BIGINT(), autoincrement=False, nullable=False
            )
        )

    # ### end Alembic commands ###
